language: python

python:
    - "3.5"

services:
  - docker

sudo: required

cache:
  - directories:
    - node_modules
    - course_discovery/static/bower_components

before_install:
    - docker-compose -f .travis/docker-compose-travis.yml up -d

script:
    - docker exec course-discovery /edx/app/discovery/discovery/.travis/run_tests.sh

after_success:
    - pip install -U codecov
    - docker exec course-discovery /edx/app/discovery/discovery/.travis/run_coverage.sh
    - codecov
