language: python

python:
    - "3.5"

services:
  - docker

sudo: required

# Cache the pip directory. "cache: pip" doesn't work due to install override. See https://github.com/travis-ci/travis-ci/issues/3239.
cache:
  - directories:
    - $HOME/.cache/pip
    - node_modules
    - course_discovery/static/bower_components

before_install:
    - docker-compose -f docker-compose.yml up -d

script:
    - docker exec course-discovery /edx/app/discovery/discovery/.travis/run_tests.sh

after_success:
    - pip install -U codecov
    - docker exec course-discovery /edx/app/discovery/discovery/.travis/run_coverage.sh
    - codecov
